// halt = stop the program
pub const HALT: usize = 0x00;
// const = push a constant onto the stack
pub const CONST: usize = 0x01;
// add = add two values together
pub const ADD: usize = 0x02;
// sub = subtract two values
pub const SUB: usize = 0x03;
// mul = multiply two values
pub const MUL: usize = 0x04;
// div = divide two values
pub const DIV: usize = 0x05;
// mod = modulo of two values
// pub const MOD: usize = 0x06;
